
run:
	python3 bot.py run

train-nlu:
	python3 -m rasa_nlu.train -c nlu_model_config.json --fixed_model_name current

train-dialogue:
	python3 bot.py train-dialogue

interactive-story-training:
	python3 interactive_training.py
